package com.ipc.proyectomc2;

import guru.nidi.graphviz.engine.Format;
import guru.nidi.graphviz.engine.Graphviz;
import guru.nidi.graphviz.model.MutableGraph;
import guru.nidi.graphviz.parse.Parser;
//import java.awt.BorderLayout;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author David
 */
public class GrafoV extends javax.swing.JFrame {
    private Grafo grafo = new Grafo();
    /**
     * Creates new form GrafoV
     */
    public GrafoV() {
        initComponents();
        setLocationRelativeTo(null);
        txtVertices.setSize(64, 26);
        
    }
    
    private void actualizarVisualizacionGrafo(JLabel grafoImageLabel, String dot) {
        try {
            Parser parser = new Parser();
            MutableGraph g = parser.read(dot);
            ByteArrayOutputStream imageStream = new ByteArrayOutputStream();
            Graphviz.fromGraph(g).render(Format.PNG).toOutputStream(imageStream);
            byte[] imageBytes = imageStream.toByteArray();
            BufferedImage image = ImageIO.read(new ByteArrayInputStream(imageBytes));
            ImageIcon icon = new ImageIcon(image);
            grafoImageLabel.setIcon(icon);
            grafoImageLabel.repaint();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        controlPanel = new javax.swing.JPanel();
        aristasPanel = new javax.swing.JPanel();
        lblAristas = new javax.swing.JLabel();
        txtAristaFin = new javax.swing.JTextField();
        btnAristas = new javax.swing.JButton();
        txtAristaInicio = new javax.swing.JTextField();
        checkAristas = new javax.swing.JCheckBox();
        lblTitulo = new javax.swing.JLabel();
        verticesPanel = new javax.swing.JPanel();
        lblVetices = new javax.swing.JLabel();
        txtVertices = new javax.swing.JTextField();
        btnVetices = new javax.swing.JButton();
        txtInicio = new javax.swing.JTextField();
        VisualPanel = new javax.swing.JPanel();
        btnGrafico = new javax.swing.JButton();
        btnRecorrido = new javax.swing.JButton();
        btnDFS = new javax.swing.JButton();
        grafosPane = new javax.swing.JPanel();
        lblGrafo = new javax.swing.JLabel();
        lblRecorrido = new javax.swing.JLabel();
        lblDFS = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Algoritmo DFS");
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setSize(new java.awt.Dimension(850, 700));

        controlPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aristasPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAristas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAristas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAristas.setText("Aristas");
        aristasPanel.add(lblAristas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, -1));

        txtAristaFin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAristaFin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        aristasPanel.add(txtAristaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 170, 40));

        btnAristas.setText("Ingresar");
        btnAristas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAristasActionPerformed(evt);
            }
        });
        aristasPanel.add(btnAristas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 410, -1));

        txtAristaInicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAristaInicio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        aristasPanel.add(txtAristaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 140, 40));

        checkAristas.setText("dirigida");
        aristasPanel.add(checkAristas, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 20, -1, 40));

        controlPanel.add(aristasPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 410, 110));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Control del Grafo");
        controlPanel.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 789, -1));

        verticesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVetices.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblVetices.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVetices.setText("Vertices");
        verticesPanel.add(lblVetices, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, -1));

        txtVertices.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtVertices.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVertices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVerticesActionPerformed(evt);
            }
        });
        verticesPanel.add(txtVertices, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 360, 40));

        btnVetices.setText("Ingresar");
        btnVetices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeticesActionPerformed(evt);
            }
        });
        verticesPanel.add(btnVetices, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 360, -1));

        controlPanel.add(verticesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 360, 110));

        txtInicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtInicio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        controlPanel.add(txtInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 680, -1));

        VisualPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGrafico.setText("Generar Grafo");
        btnGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficoActionPerformed(evt);
            }
        });
        VisualPanel.add(btnGrafico, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 259, 50));

        btnRecorrido.setText("Generar Recorrido");
        btnRecorrido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecorridoActionPerformed(evt);
            }
        });
        VisualPanel.add(btnRecorrido, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 0, 259, 50));

        btnDFS.setText("Generar Grafo DFS");
        btnDFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDFSActionPerformed(evt);
            }
        });
        VisualPanel.add(btnDFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 0, 259, 50));

        grafosPane.setLayout(new java.awt.GridLayout(1, 3, 5, 5));
        grafosPane.add(lblGrafo);
        grafosPane.add(lblRecorrido);
        grafosPane.add(lblDFS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(controlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(VisualPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(grafosPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(VisualPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(grafosPane, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtVerticesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVerticesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVerticesActionPerformed

    private void btnDFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDFSActionPerformed
        String idInicio = txtInicio.getText();
            if (grafo.obtenerVertice(idInicio) == null) {
                System.out.println("El vértice de inicio no existe en el grafo. Por favor, ingrese un vértice válido.");
            } else {
                var recorridoDFS = grafo.dfs(idInicio);
                Grafo grafoDFS = grafo.generarGrafoRecorridoDFS(recorridoDFS);
                String dot = grafoDFS.generarDot();
                actualizarVisualizacionGrafo(lblDFS, dot);
            }
    }//GEN-LAST:event_btnDFSActionPerformed

    private void btnVeticesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeticesActionPerformed
        grafo.agregarVertice(new Vertice(txtVertices.getText()));
            txtVertices.setText("");
    }//GEN-LAST:event_btnVeticesActionPerformed

    private void btnAristasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAristasActionPerformed
        Vertice fin = grafo.obtenerVertice(txtAristaFin.getText());
            Vertice inicio = grafo.obtenerVertice(txtAristaInicio.getText());
            if (inicio != null && fin != null) {
                grafo.agregarArista(new Arista(inicio, fin, checkAristas.isSelected()));
                txtAristaFin.setText("");
                txtAristaInicio.setText("");
            }
    }//GEN-LAST:event_btnAristasActionPerformed

    private void btnGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficoActionPerformed
        String dot = grafo.generarDot();
            actualizarVisualizacionGrafo(lblGrafo, dot);
    }//GEN-LAST:event_btnGraficoActionPerformed

    private void btnRecorridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecorridoActionPerformed
        String idInicio = txtInicio.getText();
                if (grafo.obtenerVertice(idInicio) == null) {
                    System.out.println("El vértice de inicio no existe en el grafo. Por favor, ingrese un vértice válido.");
                } else {
                    var recorridoDFS = grafo.dfs(idInicio);

                    // Utiliza el código proporcionado anteriormente para generar el grafo de recorrido DFS y su representación en DOT
                    Grafo grafoDFS = grafo.generarGrafoRecorridoDFS(recorridoDFS);
                    String dot = grafo.generarDotRecorrido(recorridoDFS, grafoDFS.obtenerAristas());

                    actualizarVisualizacionGrafo(lblRecorrido, dot);
                }
    }//GEN-LAST:event_btnRecorridoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrafoV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrafoV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrafoV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrafoV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GrafoV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel VisualPanel;
    private javax.swing.JPanel aristasPanel;
    private javax.swing.JButton btnAristas;
    private javax.swing.JButton btnDFS;
    private javax.swing.JButton btnGrafico;
    private javax.swing.JButton btnRecorrido;
    private javax.swing.JButton btnVetices;
    private javax.swing.JCheckBox checkAristas;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JPanel grafosPane;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAristas;
    private javax.swing.JLabel lblDFS;
    private javax.swing.JLabel lblGrafo;
    private javax.swing.JLabel lblRecorrido;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVetices;
    private javax.swing.JTextField txtAristaFin;
    private javax.swing.JTextField txtAristaInicio;
    private javax.swing.JTextField txtInicio;
    private javax.swing.JTextField txtVertices;
    private javax.swing.JPanel verticesPanel;
    // End of variables declaration//GEN-END:variables
}
